#ifndef PICO_KEYBOARD_RT_HARDWARE_CONFIG_H
#define PICO_KEYBOARD_RT_HARDWARE_CONFIG_H

// Pico-PIO-USB uses DPDM ordering: D- is the GPIO immediately after D+.
enum {
    PICO_KEYBOARD_UART_TX_GPIO = 0u,
    PICO_KEYBOARD_UART_RX_GPIO = 1u,
    PICO_KEYBOARD_MODE_GPIO = 2u,
    PICO_KEYBOARD_PIO_USB_DP_GPIO = 12u,
    PICO_KEYBOARD_PIO_USB_DM_GPIO = 13u,
    PICO_KEYBOARD_NATIVE_DEVICE_RHPORT = 0u,
    PICO_KEYBOARD_PIO_HOST_RHPORT = 1u,
    PICO_KEYBOARD_RP2350A_GPIO_COUNT = 30u,
};

#if defined(__cplusplus)
#define PICO_KEYBOARD_STATIC_ASSERT(condition, message) \
    static_assert((condition), message)
#else
#define PICO_KEYBOARD_STATIC_ASSERT(condition, message) \
    _Static_assert((condition), message)
#endif

PICO_KEYBOARD_STATIC_ASSERT(
    PICO_KEYBOARD_PIO_USB_DM_GPIO == PICO_KEYBOARD_PIO_USB_DP_GPIO + 1u,
    "Pico-PIO-USB DPDM wiring requires D- to follow D+");
PICO_KEYBOARD_STATIC_ASSERT(
    PICO_KEYBOARD_UART_TX_GPIO < PICO_KEYBOARD_RP2350A_GPIO_COUNT &&
        PICO_KEYBOARD_UART_RX_GPIO < PICO_KEYBOARD_RP2350A_GPIO_COUNT,
    "UART0 pins must be valid RP2350A GPIOs");
PICO_KEYBOARD_STATIC_ASSERT(
    PICO_KEYBOARD_PIO_USB_DP_GPIO < PICO_KEYBOARD_RP2350A_GPIO_COUNT,
    "PIO-USB D+ must be a valid RP2350A GPIO");
PICO_KEYBOARD_STATIC_ASSERT(
    PICO_KEYBOARD_PIO_USB_DM_GPIO < PICO_KEYBOARD_RP2350A_GPIO_COUNT,
    "PIO-USB D- must be a valid RP2350A GPIO");
PICO_KEYBOARD_STATIC_ASSERT(
    PICO_KEYBOARD_MODE_GPIO < PICO_KEYBOARD_RP2350A_GPIO_COUNT,
    "mode input must be a valid RP2350A GPIO");
PICO_KEYBOARD_STATIC_ASSERT(
    PICO_KEYBOARD_MODE_GPIO != PICO_KEYBOARD_PIO_USB_DP_GPIO &&
        PICO_KEYBOARD_MODE_GPIO != PICO_KEYBOARD_PIO_USB_DM_GPIO,
    "mode input must not overlap PIO-USB data pins");
PICO_KEYBOARD_STATIC_ASSERT(
    PICO_KEYBOARD_UART_TX_GPIO != PICO_KEYBOARD_UART_RX_GPIO,
    "UART TX and RX must use distinct GPIOs");
PICO_KEYBOARD_STATIC_ASSERT(
    PICO_KEYBOARD_MODE_GPIO != PICO_KEYBOARD_UART_TX_GPIO &&
        PICO_KEYBOARD_MODE_GPIO != PICO_KEYBOARD_UART_RX_GPIO,
    "mode input must not overlap UART0 pins");
PICO_KEYBOARD_STATIC_ASSERT(
    PICO_KEYBOARD_PIO_USB_DP_GPIO != PICO_KEYBOARD_UART_TX_GPIO &&
        PICO_KEYBOARD_PIO_USB_DP_GPIO != PICO_KEYBOARD_UART_RX_GPIO &&
        PICO_KEYBOARD_PIO_USB_DM_GPIO != PICO_KEYBOARD_UART_TX_GPIO &&
        PICO_KEYBOARD_PIO_USB_DM_GPIO != PICO_KEYBOARD_UART_RX_GPIO,
    "PIO-USB data pins must not overlap UART0 pins");

#if defined(PICO_DEFAULT_PIO_USB_DP_PIN)
PICO_KEYBOARD_STATIC_ASSERT(
    PICO_DEFAULT_PIO_USB_DP_PIN == PICO_KEYBOARD_PIO_USB_DP_GPIO,
    "TinyUSB PIO D+ definition must match the hardware contract");
#endif
#if defined(BOARD_TUD_RHPORT)
PICO_KEYBOARD_STATIC_ASSERT(
    BOARD_TUD_RHPORT == PICO_KEYBOARD_NATIVE_DEVICE_RHPORT,
    "TinyUSB device root hub must match the hardware contract");
#endif
#if defined(BOARD_TUH_RHPORT)
PICO_KEYBOARD_STATIC_ASSERT(
    BOARD_TUH_RHPORT == PICO_KEYBOARD_PIO_HOST_RHPORT,
    "TinyUSB host root hub must match the hardware contract");
#endif

#undef PICO_KEYBOARD_STATIC_ASSERT

#endif  // PICO_KEYBOARD_RT_HARDWARE_CONFIG_H
